// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOLPeAJY2yo8-9QuT275KFsCGHEWEqVjs',
    appId: '1:721964679059:android:b32683409bf79dc48a7266',
    messagingSenderId: '721964679059',
    projectId: 'transport-app-36443',
    databaseURL: 'https://transport-app-36443-default-rtdb.firebaseio.com',
    storageBucket: 'transport-app-36443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN58h5tthuZwC5FCxrxiGA4EL4_HpFw5E',
    appId: '1:721964679059:ios:6a98f138970bd4f38a7266',
    messagingSenderId: '721964679059',
    projectId: 'transport-app-36443',
    databaseURL: 'https://transport-app-36443-default-rtdb.firebaseio.com',
    storageBucket: 'transport-app-36443.appspot.com',
    androidClientId: '721964679059-01o42131sf55isdpqp32jdlchb2kklnq.apps.googleusercontent.com',
    iosClientId: '721964679059-2lt7ds9fb1sg5d8fersvko7j0477cd20.apps.googleusercontent.com',
    iosBundleId: 'com.example.driversApp',
  );
}
